version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cti-assessment
    container_name: cti-assessment-app
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./docs:/usr/share/nginx/html
    networks:
      - cti-network

networks:
  cti-network:
    driver: bridge
